export class CollectResponse {
    objectid?: number; // 74208,
    lote?: string; //'CC02',
    codigo_ra?: number; //3,
    codigo_circuito?: number; // 200313,
    nome_circuito?: string; //'Taguatinga 200313 A3TQS',
    enderecamento?: string; //'SETOR DE DESENVOLVIMENTO ECONOMICO Q 1, 2; SETOR H NORTE CNH 1, 2, 3, 4, 5, QNH 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16; SETOR M NORTE EQNM 34/36, QNM 34',
    frequencia?: string; //'Terça, Quinta e Sábado',
    horario_inicio?: string; //'19?:00?:00',
    horario_termino?: string; //'03?:20?:00',
    tipo_de_servico?: string; //'Coleta Convencional (Porta a Porta)',
    equipamento?: string; //'Caminhão Coletor Compactador de 19 m³',
    razao_social?: string; //'Sustentare Saneamento S/A',
    local_pesagem?: string; //'UTMB P Sul',
    local_destinacao?: string; //'UTMB P Sul',
    data_inicio_vigencia?: number; //1661742000000,
    data_termino_vigencia?: number; //null,
    status?: string; //'ATIVO',
    extensao_planejamento?: number; //17865.51141405
}
